# Abstract {.unnumbered}
\begin{center}
\begin{singlespacing}
Classification of Generic Manufacturers and Competition in the Pharmaceutical Industry  

An Abstract of the Thesis by  

Mark Benmuvhar
\end{singlespacing}
\end{center}
\par
\par
\pagenumbering{roman}  
\setcounter{page}{4}
United States generic and brand pharmaceutical companies balance innovation, profit, and public health under the Drug Price Competition and Patent Term Restoration Act.  Patent expiration dates demarcate potential profit and legal risk for generic pharmaceutical companies, underscoring the importance of forecasting competition for limited revenue.  For this, modules coded in Python extracted data from Food and Drug Administration product approvals and individual product labels to create sets of brand and generic products.  Predictive models using classification methods including gradient boosted random forest algorithms were built in R to evaluate brand product patent counts, patent categories, ingredients, and packaging components as predictors of generic competition before and after brand product patent expiry.  Gradient boosted algorithms predicted generic competition before first, before last, or after last patent expiry with significant accuracy (p <0.05) of 83.3%, 68.9%, and 69.4%, respectively.  Models demonstrated the feasibility of using non-fiscal data to predict generic competition.

\newpage
