# Data Resources

## Approved Drug Products with Therapeutic Equivalence Evaluations. 25th to 42nd Editions. 

Each year, the FDA publishes the commonly referenced "Orange Book" [@fda05], an official record of all drug products approved for marketing in the United States. This book establishes which products are generic and substitutable for each innovative brand product.  It contains a record of all products discontinued from marketing.  Finally, it details which patents the brand products claim for each drug product.  These specific patents may form the basis for any infringement lawsuits brought against generic applicants in accordance with the Patent Term Restoration Act.  Details of the patents also include any regulatory exclusivity clauses that accompany each patent.  These sections differ in format and content, which may be described as follows.

Common details in each section include the drug substance name, unique application number, and product code, which enumerates differing product strengths or other variations.  Together, these establish a unique key for correlating distinct records across sections.  

The Prescription Drug Product section includes the following fields:

\textbf{Route of Administration}:  The FDA uses specific terms for how a product is introduced to the body.  This broadly differentiates products taken by mouth (oral), injected into the bloodstream (intravenous), and similar demarcations.  

\textbf{Dosage Form}:  Products intended for each route of administration may take different forms.  For example, orally administered products comprises both liquids, tablets, and capsules taken by mouth.      

\textbf{Drug Product Name}: Commercial names for the product may either be an invented trade name for the brand product, such as the cholesotrol drug Lipitor, or the name of the drug substance used in the generic product, such as acetaminophen, found in the pain treatment Tylenol.  Because the product names are not unique, they can be ignored in the analysis for this report.

\textbf{Reference Designation}:  For each unique drug substance, route of administration, and dosage form, the FDA must designate one or more products as the reference product for subsequent generic products to test against.  In certain cases, a separate product receives designation as a reference standard due to discontinuance of the original reference product or the replacement of the reference product with newer products that follow modern application requirements.

\textbf{Therapeutic Equivalence Code}: Where multiple product sources exist for a drug substance and route of administration, the FDA assigns a two letter equivalence code, such as "AB".  Generally, the first letter represents whether product substitutions are allowed ("A") or forbidden ("B"), while the second letter represents the route of administration.  Due to differences in physiological absorption or performance, a suffixed digit may differentiate product classes within the same drug substance and administration route category.  Similarly, differences in product performance may lead to the FDA adjudicating that a generic cannot be substituted for the brand.  

\textbf{Sponsor Name}:  A product's sponsor is responsible for submission and maintenance of the application.  Due to changes in corporate identity due to merger or restructuring, the sponsor name may change across editions of the Orange Book. 

\textbf{Approval Date}:  The approval date occurs when the FDA provides marketing authorization for a product after application review.   

The discontinued product section duplicates entries of the prescription drug product list except that bioequivalence codes are unlisted.  Individual product codes and strengths under an application may be withdrawn from the market while others remain marketed.  The year of discontinuance is not reported and must be implied from the Orange Book edition in which the item first occurs.   

The section entitled Prescription and OTC Drug Product Patent and Exclusivity List enumerates the following details:

\textbf{Patent Number and Expiration Date}:  For each application and product number (strength), the assigned patent number and patent expiration date are listed.  In rare cases, patent numbers may not apply to each strength in an application.  Multiple patents may be assigned to a single drug product;   

\textbf{Patent Codes}:  Codes describe if a patent pertains to the drug substance, the drug product (dosage form), or therapeutic usage area.  The usage code may be one of over 3000 four digit codes that correspond to a brief description of the clinical or treatment aspects claimed by a patent.  For example: "U-2627: Topical treatment of plaque psoriasis in patients 12 years and older."  Multiple usage codes may be assigned to a single patent;  

\textbf{Exclusivity Codes and Expiration Date}:  Exclusivity periods represent statutory prohibitions that prevent the FDA from approving generic products for a certain time period.  These arise from laws enabling new molecule development, treatment of rare diseases, clinical studies in pediatric populations, and other reasons.  Exclusivity periods may run concurrently or in serial with patents.  Multiple exclusivity codes may be assigned to a single patent.  Certain exclusivity codes, such as those for pediatric exclusivity or orphan drug designations, may be assigned to the drug product rather than a patent and are listed as independent line items.  

While the FDA maintains an electronic database of the Orange Book, the online version only captures data for the current year. Certain details are deprecated following periodic updates. As patents expire, they are removed from the online listing. As products are removed from the market, the equivalence relationship between branded and generic products is removed. To develop a comprehensive review of historical applications, it was necessary to perform data extraction from PDF renditions of the Orange Book. Historical editions were made available online via a regulatory law firm (Hyman, Phelps, McNamarra) following a Freedom of Information Act request to the FDA for electronic copies.  Due to illegibility of the original scans, data could not be extracted from editions prior to the 25th edition.  However, an archival project existed online that captured key elements of the patent history (Drug Database, N.D).  Researchers for this database had also encountered legibility challenges and had performed manual entry.  In turn, a portion of these entries were manually against the Orange Book and acceptable supplements for the extracted patent information.   

A description of the parsed data is presented in Table \@ref(tab:OBSummary). Details related to data extraction from the PDF file and associated challenges are reported in Section 4 - Methods.  

```{r OBSummary, include = TRUE}
tibble(Section = c("Marketed Products", "Discontinued Products", "Patents"), 'Line Items' = c(285407, 222169, 182713), "Unique Products, Manufacturers, and Strengths" = c(71321, 53339, 76366), "Unique Products and Manufacturers" = c(32510, 20940, 2628), "Unique Patents" = c("NA", "NA", 40165)) %>%
  kbl(booktabs = TRUE, 
      caption = "Record Summary from the FDA Orange Book, 25th to 42nd Edition",
      position = "h",
      align = "c") %>%
  kable_styling(full_width = F,
                ) %>%
  column_spec(c(3,4), width = "1.3in")
```

## Drug Product Labels
The FDA has required and collected product labeling information for all marketed drug products using a structured XML format since 2005.  Complete details of the structured label content and hierarchical XML scheme are outlined in the FDA's implementation guidance [@cber18].  All XML files are publicly available and are maintained by the National Library of Medicine @nlm22. Among the exhaustive information on clinical studies, safety, efficacy, and use, each label also describes the qualitative composition and descriptive details of each drug product. These data included interesting features such as product size, shape, color, and imprinting. Each label references an approved application number and can be joined with Orange Book entries to characterize products. The dataset contains 46,640 entries provided as zipped XML files.  The labels reference 1,194 unique ingredients and 60 distinct packaging configurations.

In the product labels, ingredient names are paired with a unique ingredient identifier (UNII), which provides an unambgiuous alphanumeric code for the underlying molecular structure.  Some variance in product names has occurred across manufacturers and years of label revision.  Therefore, ingredient names were standardized based on the name associated with the first occurrence of each UNII.  No standardization was performed on the packaging components.

The product label archives are limited in that they are not maintained for discontinued products.  Approximately half of the distinct application numbers extracted from the Orange Book do not have associated package labels.  Therefore, analysis using ingredients and packaging may exhibit a "survivor's bias".  Analysis using these features reflect a subclasses of products that have remained on the market rather than being discontinued.  While features of discontinued products may contradict the analysis, I am unaware of any accessible sources for the information.  