# Statement of Security and Ethical Considerations  

For this thesis, I will make security and ethical considerations concerning the availability and privacy of data used in the research as well as to the impact of conclusions realized from the analysis. Broadly, this will consider the public nature of the Orange Book information and product labels. Exploration of these data sets will attempt to establish broad market patterns and could characterize individual companies. To the extent that these relationships exist, the derivation of private practices from public data merits ethical review.  

The ethical considerations of the study acknowledge that the data is derived from public sources and government records. The subject of drug approvals is corporate rather than individual, and issues of personal privacy are not material. To the extent that this report seeks to discover patterns associated with drug development and approval, the ethical considerations demand adherence to the professional code of conduct established by the American Statistical Association [@asa18].  As the outcome of this study may allude to business practices reflecting trade secrets, it does so based on a practiced reading of public record and proper application of statistical techniques. 
