# Discussion

Overall, the model weighting on product approval prior to patent expiry merits a question as to whether generic competition is a matter of timing.  Given enough notice, some generic competition seems likely to occur regardless of the complexity of the dosage form or patent portfolio.  However, the models also singled out “injectable”, “liquids”, and “modified release” dosage forms as predictive features.  Each of these reflect differing levels of complexity, which suggests that product design may matter.  

While boosted gradient models accurately predicted generic competition with multiple data sets, the 15 – 20% loss in accuracy between test and training sets suggests the data was overfit during training.  With other algorithms, very few models achieved greater than 90% training set accuracy, and few models saw more than 10% decline in accuracy between the training and test set analysis.  By oversampling the training set, the event distributions were artificially changed from 15-30% to 50%.  While this was intended to improve model discrimination by providing equal visibility to sample features, it may have allowed the boosted gradient methods to overweight test set characteristics.  Conservative learning rates and aggressive random sampling and variable replacement parameters may have tempered training, leading to acceptable accuracy for the test sets.  

Across all models, the capability for predicting competition after last patent expiry belies some complexity with filtering the basis set data analysis.  Using too many exclusion criteria can produce insufficient cases for analysis or a rank-deficient matrix.  Branded products used in this study were approved no later than 2010.  Thus, patent expiry may be well after the final Orange Book data point in 2022.  This creates a situation where the analysis may be biased towards a simple has / does not have patent discrimination.  Likewise, limiting the analysis to only the 4 most prominent routes of administration produced a tradeoff between additional datapoints and complexity in the routes of administration.  Although these windows highlight a priori choices about the data, setting broader windows or a systemic evaluation may have provided greater insights.  

From this study, the market analysis may represent the largest achievement.  For many industry insiders, there is often an intuitive feel for competitive aspects without having a quantitative picture of the competitive space.  This study provides a succinct, longitudinal summary of the interplay between brand and generic companies.  More important, the compiled data provides a basis for future studies into how band and generic companies differ.  For example, differences between generic and branded formulations can be compared, while market segmentation may be performed on companies based on product selection, time-to-market, and product composition.  Recognizing that competition reflects financial viability, the data set could readily be joined with sales cost and sale volume data.  